### ISSUE TITLE
brunnhilde-gui doesn't launch in BitCurator 2.0.8

### ISSUE THREAD

**Issue by nvanderperren** [tw4l/brunnhilde-gui#3]
I cloned the repository and did `sudo bash install`. I can see the icon in "Forensics and Reporting", but the app isn't launched when I click on the icon. 

I use Bitcurator 2.0.8.

This is the list of files in the folder. 
```
bcadmin@reslab:~$ ls -la Desktop/Forensics\ and\ Reporting
total 76
drwxr-xr-x 2 bcadmin bcadmin 4096 nov 28 15:44  .
drwxr-xr-x 7 bcadmin bcadmin 4096 nov 28 14:41  ..
-rwxr-xr-x 1 bcadmin bcadmin  530 nov 13 02:00  bcdat.desktop
-rwxr-xr-x 1 bcadmin bcadmin  516 nov 13 02:00  bcgui.desktop
-rwxr-xr-x 1 bcadmin bcadmin  518 nov 13 02:00  bcmnt.desktop
-rwxr-xr-x 1 bcadmin bcadmin  197 nov 13 02:00  BEViewer.desktop
-rwxr-xr-x 1 bcadmin bcadmin  240 nov 13 02:00  brunnhilde.desktop
-rwxr-xr-x 1 bcadmin bcadmin  131 nov 28 15:44 'Brunnhilde GUI.desktop'
-rwxr-xr-x 1 bcadmin bcadmin  232 nov 13 02:00  disktype.desktop
-rwxr-xr-x 1 bcadmin bcadmin  229 nov 13 02:00  fiwalk.desktop
-rwxr-xr-x 1 bcadmin bcadmin  152 nov 13 02:00  fslint.desktop
-rwxr-xr-x 1 bcadmin bcadmin  229 nov 13 02:00  md5deep.desktop
-rwxr-xr-x 1 bcadmin bcadmin  238 nov 13 02:00  nsrllookup.desktop
-rwxr-xr-x 1 bcadmin bcadmin  238 nov 13 02:00  photorec.desktop
-rwxr-xr-x 1 bcadmin bcadmin  386 nov 13 02:00  pyexiftoolgui.desktop
-rwxr-xr-x 1 bcadmin bcadmin  235 nov 13 02:00  regripper.desktop
-rwxr-xr-x 1 bcadmin bcadmin  239 nov 13 02:00  sdhash.desktop
-rwxr-xr-x 1 bcadmin bcadmin  236 nov 13 02:00  ssdeep.desktop
-rwxr-xr-x 1 bcadmin bcadmin  253 nov 13 02:00  testdisk.desktop
```

**Comment by tw4l** [comment]
Thanks for reporting this issue! I think you need to install PyQt5 with `sudo pip3 install pyqt5`, and then the launcher should work. If you want to verify this is the problem, try launching the GUI directory with `python3 /usr/share/brunnhilde-gui/main.py` and see the error message it gives you. When I tried on a fresh BitCurator install, I got the following: `ModuleNotFoundError: No module named 'PyQt5'`. Installing pyqt5 with pip3 fixed it for me.

Looking at the README, it's not clear that this step is necessary in BitCurator. So if this fix works for you, please let me know and I'll update the README. Thanks!

**Comment by nvanderperren** [comment]
Yes! Fix works! Thank you for your quick response and solution!

**Comment by tw4l** [comment]
Glad to hear it! I'm closing the issue but feel free to re-open if you run into any other issues.
