### ISSUE TITLE
Desktop files in BitCurator 4.4.0

### ISSUE THREAD

**Issue by WhenSkiesAbove** [tw4l/brunnhilde-gui#4]
Hi Tessa,

I just installed this on a fresh instance of BitCurator 4.4.0 and noticed that desktop icons don't really work anymore (may be the case on earlier versions too, I went straight from 2.2.8 to 4.4.0 so I don't know when it changed). Based on a quick google, I think it's whatever-the-heck version of Ubuntu it now runs on. Seems desktop files now have to go into /usr/share/applications and need to include a 'Categories=Forensics and Reporting' (or whatever category you want) tag to show up in the Applications drop-down. Not sure if there's a better way to do it, but that worked for me. Maybe it just needs to be added to the instructions. I definitely didn't know it without having to Google it.

Thanks!

Jarad

**Comment by tw4l** [comment]
Hi Jarad, thanks for bringing this to my attention and doing research into the fix! I'll do my best to get this patched this week - just wanna do some testing with a few versions of BitCurator and so need a little time to spin up a VM and do some testing.

**Comment by WhenSkiesAbove** [comment]
Awesome - thanks Tessa! Appreciate it.

Cheers,
Jarad

**Comment by tw4l** [comment]
Hi Jarad - apologies it took me a while but I've pushed changes so that the `install` script now installs the desktop file correctly in BitCurator 4. I've also added a new `install-bc2-ubuntu18` script for older version of BitCurator.

Thanks for the helpful info and the nudge!

**Comment by WhenSkiesAbove** [comment]
That's awesome - thanks Tessa!
